### ISSUE TITLE
HTML -> typescript conexiones puntuales 

### ISSUE THREAD

**Issue by stphnVi** [valeriam07/Proyecto-I-Datos-II#2]
Las implementaciones de Addons() con C++ en Javascript genera que el uso y la creacion de variables las cuales contienen el contenido desde C++ sea más complicado tomarlas por el tipo de escritura del lenguage de Typescript el cual posteriormente se pasa a javascript, esto ha generado una serie de retrasos.

**Comment by stphnVi** [comment]
Las implementaciones con Addons fueron retiradas de la programación.

**Comment by stphn1117** [comment]
Generar el .so y conectar la extension con los archivos generados por el mismo
